### ISSUE TITLE
`laminas/laminas-zendframework-bridge` in skeleton applications

### ISSUE THREAD

**Issue by boesing** [laminas/technical-steering-committee#91]
I wonder if we should add the `replace` keyword for the `laminas/laminas-zendframework-bridge` in the skeleton app.

```
{
    "replace": {
        "laminas/laminas-zendframework-bridge": "*"
    }
}
```

Imho, no one should create a new laminas package along with modules which are still not migrated until now,
So the bridge won't have any meaning. This is also the root cause on why we're facing this issue.

Maybe something we want to consider in the TSC tomorrow. Gonna add an agenda item.

_Originally posted by @boesing in https://github.com/laminas/laminas-test/issues/38#issuecomment-890487451_

**Comment by rieschl** [comment]
totally agree.
In addition, the presence of that bridge is "quite" costly. We did some performance tweaks lately and discovered, that the `\Laminas\ZendFrameworkBridge\Autoloader` alone takes up ~15% of a preflight request. We didn't benchmark the `ConfigPostProcessor` because it's not an issue when the config is cached but probably lots of live sits out there don't cache their config.

**Comment by boesing** [comment]
Yah, we did that for the `laminas/laminas-cache-storage-adapter-*` packages in v2.10+ as well:
https://github.com/laminas/laminas-cache/tree/2.10.x#avoid-unused-cache-adapters-are-being-installed

Could be easily added to the package. However, I don't think that anyone ever opened the README file for that package as they're not aware of the magic behind it. So it might be worth adding it to the README of either `mezzio/mezzio-skeleton` or `laminas/laminas-mvc-skeleton`.

**Comment by rieschl** [comment]
> Could be easily added to the package. However, I don't think that anyone ever opened the README file for that package as they're not aware of the magic behind it. So it might be worth adding it to the README of either `mezzio/mezzio-skeleton` or `laminas/laminas-mvc-skeleton`.

Most people won't just stumble upon that, but for those who search for it, it might be a good hint.

> But AFAIK, @Ocramius still has an [agenda item](https://github.com/laminas/technical-steering-committee/blob/8f72cf6af75f22436d752ce7e7c0f92c23336666/meetings/agenda.md#remove-laminaslaminas-zendframework-bridge-dependency-from-our-packages) regarding the bridge and thus we might get rid of it quite soonish depending on how we vote on it in the next TSC meeting.

Yes, but that don't help people who have added the `laminas/laminas-zendframework-bridge` to their project's `composer.json`, or worse, if they didn't add it and the bridge is removed in all laminas-* packages, their ModuleManager will explode because they have `'Laminas\ZendFrameworkBridge'` in their modules.config but the package isn't installed anymore.
Or is the component-installer smart enough to remove the entry of the module even if it wasn't a root dependency?


> Maybe it is worth adding some core-checks to the bridge component which determines if it is still necessary to hook into the autoloader. Not sure how this could be achieved.

You could throw a `E_USER_DEPRECATED` but it's probable either annoying or unnoticed 🙂. A better place could be in the `laminas-dependency-plugin` and print a warning when a composer install/update is done?

**Comment by boesing** [comment]
> Or is the component-installer smart enough to remove the entry of the module even if it wasn't a root dependency?

It actually is. It doesnt care about why a component is installed. It just get the Info that it is installed or uninstalled 👌🏻

**Comment by geerteltink** [comment]
If all skeleton apps and required packages switched to laminas / mezzio packages then it's not needed anymore. As you mention, it's used for fresh projects only.

**Comment by Ocramius** [comment]
Considering discussion happened around https://github.com/laminas/technical-steering-committee/blob/8f72cf6af75f22436d752ce7e7c0f92c23336666/meetings/agenda.md#remove-laminaslaminas-zendframework-bridge-dependency-from-our-packages, is this topic still valid?

**Comment by michalbundyra** [comment]
Skeleton is kinda different. I am surprised we do have it here. I think for skeletons we should even have already bridge in replace, so it is not installed for new projects.

**Comment by boesing** [comment]
I guess we can close this. I'll create an issue in `mezzio/mezzio-skeleton` instead to get rid of the bridge in the skeleton package.
